---
abstract: unknown
author:
  - 'Mike Rylander <miker@esilibrary.com>'
  - 'Thomas Berezansky <tsbere@mvlc.org>'
  - 'Jared Camins-Esakov <jcamins@cpbibliography.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: OpenILS-QueryParser
no_index:
  directory:
    - t
    - inc
requires:
  JSON: 2.17
  Test::More: 0
version: 0.01
